// FairTrade Tycoon - Game Decisions for 7 Rounds
// Mỗi quyết định ảnh hưởng đến Money, Fairness, Reputation

export interface DecisionOption {
  id: string; // Unique ID cho mỗi option
  text: string;
  moneyChange: number; // Thay đổi tiền (có thể âm hoặc dương)
  fairnessChange: number; // -3 đến +3
  reputationChange: number; // -3 đến +3
  description?: string; // Mô tả thêm về hậu quả
  bonusMultiplier?: number; // Hệ số nhân thêm cho các vòng sau (nếu có)
}

export interface GameDecision {
  round: number;
  title: string;
  description: string;
  options: DecisionOption[];
}

// Decisions by Business Type
export const decisionsByBusiness: Record<string, GameDecision[]> = {
  // FAIRTRADE COFFEE FARM
  coffee: [
    {
      round: 1,
      title: "Khởi Đầu Mùa Vụ",
      description: "Quyết định về đầu tư hạt giống cho mùa vụ đầu tiên",
      options: [
        {
          id: "coffee-1-a",
          text: "Đầu tư hạt giống chất lượng cao",
          moneyChange: -4000,
          fairnessChange: 2,
          reputationChange: 1,
          description: "Chi phí cao nhưng hiệu quả tốt hơn và bền vững",
        },
        {
          id: "coffee-1-b",
          text: "Mua hạt giống giá rẻ từ nguồn không rõ",
          moneyChange: -3000,
          fairnessChange: -2,
          reputationChange: -1,
          description: "Tiết kiệm chi phí nhưng thiếu minh bạch",
        },
        {
          id: "coffee-1-c",
          text: "Giữ vốn, không đầu tư thêm",
          moneyChange: 0,
          fairnessChange: 0,
          reputationChange: 0,
          description: "An toàn nhưng không có lợi thế cạnh tranh",
        },
      ],
    },
    {
      round: 2,
      title: "Tuyển Dụng Lao Động",
      description: "Lựa chọn chính sách nhân sự và tiền lương",
      options: [
        {
          id: "coffee-2-a",
          text: "Thuê lao động địa phương, trả công công bằng",
          moneyChange: -4000,
          fairnessChange: 3,
          reputationChange: 2,
          description: "Xây dựng uy tín và trách nhiệm cộng đồng",
        },
        {
          id: "coffee-2-b",
          text: "Thuê lao động giá rẻ thời vụ",
          moneyChange: -2000,
          fairnessChange: -3,
          reputationChange: -2,
          description: "Tiết kiệm chi phí nhưng mất lòng người",
        },
        {
          id: "coffee-2-c",
          text: "Tự quản lý và thuê ít nhân công",
          moneyChange: -1000,
          fairnessChange: 1,
          reputationChange: 0,
          description: "Cân bằng chi phí và đạo đức",
        },
      ],
    },
    {
      round: 3,
      title: "Giao Thương Xuất Khẩu",
      description: "Chọn kênh phân phối để xuất khẩu cà phê",
      options: [
        {
          id: "coffee-3-a",
          text: "Xuất khẩu qua tổ chức FairTrade",
          moneyChange: 10000,
          fairnessChange: 2,
          reputationChange: 2,
          description: "Lợi nhuận ổn định, đảm bảo tiêu chuẩn đạo đức",
        },
        {
          id: "coffee-3-b",
          text: "Bán qua thương lái trung gian không chứng nhận",
          moneyChange: 15000,
          fairnessChange: -2,
          reputationChange: -1,
          description: "Lợi nhuận cao nhưng thiếu minh bạch",
        },
        {
          id: "coffee-3-c",
          text: "Chia 50% hàng cho thương lái, 50% cho FairTrade",
          moneyChange: 12000,
          fairnessChange: 0,
          reputationChange: 1,
          description: "Cân bằng giữa lợi nhuận và uy tín",
        },
      ],
    },
    {
      round: 4,
      title: "Mở Rộng Quy Mô",
      description: "Quyết định chiến lược phát triển doanh nghiệp",
      options: [
        {
          id: "coffee-4-a",
          text: "Mở rộng bằng tái đầu tư bền vững (đào tạo nông dân)",
          moneyChange: -8000,
          fairnessChange: 2,
          reputationChange: 1,
          description: "Đầu tư dài hạn, hiệu quả tăng 25% ở vòng 6-7",
        },
        {
          id: "coffee-4-b",
          text: "Vay vốn ngân hàng lãi suất cao để mở rộng nhanh",
          moneyChange: 10000,
          fairnessChange: 0,
          reputationChange: -1,
          description: "Tăng vốn ngay nhưng có áp lực nợ",
        },
        {
          id: "coffee-4-c",
          text: "Giữ quy mô nhỏ, không mở rộng",
          moneyChange: 0,
          fairnessChange: 1,
          reputationChange: 0,
          description: "An toàn, ổn định nhưng hạn chế tăng trưởng",
        },
      ],
    },
    {
      round: 5,
      title: "Khủng Hoảng Thị Trường",
      description: "Giá cà phê thế giới sụt giảm, bạn phải quyết định nhanh",
      options: [
        {
          id: "coffee-5-a",
          text: "Giữ cam kết bán giá công bằng, chấp nhận lỗ nhẹ",
          moneyChange: -5000,
          fairnessChange: 2,
          reputationChange: 2,
          description: "Mất tiền nhưng giữ được lòng tin khách hàng",
        },
        {
          id: "coffee-5-b",
          text: "Giảm chất lượng sản phẩm để giữ giá",
          moneyChange: 8000,
          fairnessChange: -3,
          reputationChange: -2,
          description: "Tăng lợi nhuận ngắn hạn nhưng mất uy tín",
        },
        {
          id: "coffee-5-c",
          text: "Cắt giảm chi phí marketing, tập trung nội địa",
          moneyChange: 0,
          fairnessChange: 1,
          reputationChange: -1,
          description: "Tiết kiệm chi phí, chuyển hướng thị trường",
        },
      ],
    },
    {
      round: 6,
      title: "Cơ Hội Đầu Tư",
      description: "Xuất hiện cơ hội đầu tư vào công nghệ và đối tác mới",
      options: [
        {
          id: "coffee-6-a",
          text: "Đầu tư vào dây chuyền chế biến sạch",
          moneyChange: -10000,
          fairnessChange: 3,
          reputationChange: 3,
          description: "Chi phí cao nhưng tăng 30% lợi nhuận vòng 7",
        },
        {
          id: "coffee-6-b",
          text: "Nhận đầu tư từ đối tác không minh bạch",
          moneyChange: 15000,
          fairnessChange: -2,
          reputationChange: -3,
          description: "Tiền nhanh nhưng rủi ro uy tín cao",
        },
        {
          id: "coffee-6-c",
          text: "Không đầu tư, giữ nguyên quy mô",
          moneyChange: 0,
          fairnessChange: 1,
          reputationChange: 0,
          description: "Ổn định, không thay đổi",
        },
      ],
    },
    {
      round: 7,
      title: "Tổng Kết Mùa Vụ",
      description: "Vòng cuối cùng - quyết định kết thúc năm kinh doanh",
      options: [
        {
          id: "coffee-7-a",
          text: "Tổ chức lễ tri ân người lao động và khách hàng",
          moneyChange: -2000,
          fairnessChange: 1,
          reputationChange: 3,
          description: "Đầu tư vào mối quan hệ dài hạn",
        },
        {
          id: "coffee-7-b",
          text: "Tăng giá bán để tối đa hóa lợi nhuận",
          moneyChange: 10000,
          fairnessChange: -2,
          reputationChange: -2,
          description: "Thu lợi nhuận cao nhưng mất niềm tin",
        },
        {
          id: "coffee-7-c",
          text: "Tái đầu tư cho cộng đồng địa phương",
          moneyChange: -3000,
          fairnessChange: 3,
          reputationChange: 2,
          description: "Xây dựng di sản bền vững cho cộng đồng",
        },
      ],
    },
  ],

  // ETHICAL TEXTILE WORKSHOP
  textile: [
    {
      round: 1,
      title: "Khởi động xưởng",
      description: "Bạn cần thiết lập cơ sở hạ tầng ban đầu cho xưởng dệt may.",
      options: [
        {
          id: "textile-1-a",
          text: "Mua máy may tiết kiệm năng lượng",
          description: "Chi phí cao nhưng thân thiện môi trường. Tăng năng suất 15% từ vòng 3.",
          moneyChange: -7500,
          fairnessChange: 2,
          reputationChange: 1,
          bonusMultiplier: 1.15,
        },
        {
          id: "textile-1-b",
          text: "Mua thiết bị cũ rẻ tiền",
          description: "Tiết kiệm chi phí nhưng kém bền vững. Lợi nhuận +10% tạm thời.",
          moneyChange: -3500,
          fairnessChange: -1,
          reputationChange: -1,
          bonusMultiplier: 1.1,
        },
        {
          id: "textile-1-c",
          text: "Thuê lại xưởng địa phương",
          description: "Hỗ trợ cộng đồng địa phương",
          moneyChange: -4500,
          fairnessChange: 1,
          reputationChange: 0,
        },
      ],
    },
    {
      round: 2,
      title: "Tuyển nhân công",
      description: "Chọn cách thức tuyển dụng và đãi ngộ nhân viên.",
      options: [
        {
          id: "textile-2-a",
          text: "Trả lương công bằng cho thợ may",
          description: "Đảm bảo điều kiện làm việc tốt",
          moneyChange: -5500,
          fairnessChange: 3,
          reputationChange: 2,
        },
        {
          id: "textile-2-b",
          text: "Thuê thời vụ giá rẻ",
          description: "Giảm chi phí nhưng ảnh hưởng danh tiếng. Lợi nhuận +5%.",
          moneyChange: -1500,
          fairnessChange: -3,
          reputationChange: -2,
          bonusMultiplier: 1.05,
        },
        {
          id: "textile-2-c",
          text: "Đào tạo thợ trẻ địa phương",
          description: "Đầu tư vào phát triển kỹ năng. Tăng năng suất 10% ở vòng 4–5.",
          moneyChange: -3000,
          fairnessChange: 2,
          reputationChange: 1,
          bonusMultiplier: 1.1,
        },
      ],
    },
    {
      round: 3,
      title: "Lựa chọn nguyên liệu",
      description: "Quyết định nguồn nguyên liệu cho sản xuất.",
      options: [
        {
          id: "textile-3-a",
          text: "Dùng sợi tái chế thân thiện môi trường",
          description: "Bền vững nhưng chi phí cao",
          moneyChange: -6500,
          fairnessChange: 3,
          reputationChange: 1,
        },
        {
          id: "textile-3-b",
          text: "Nhập sợi giá rẻ không chứng nhận",
          description: "Tiết kiệm nhưng thiếu trách nhiệm. Lợi nhuận ngắn hạn +15%.",
          moneyChange: -2500,
          fairnessChange: -2,
          reputationChange: -2,
          bonusMultiplier: 1.15,
        },
        {
          id: "textile-3-c",
          text: "Kết hợp 50% tái chế + 50% nhập khẩu",
          description: "Cân bằng giữa chi phí và bền vững",
          moneyChange: -4500,
          fairnessChange: 1,
          reputationChange: 0,
        },
      ],
    },
    {
      round: 4,
      title: "Mở rộng thị trường",
      description: "Tìm kiếm cơ hội kinh doanh mới.",
      options: [
        {
          id: "textile-4-a",
          text: "Tham gia hội chợ công bằng quốc tế",
          description: "Xây dựng thương hiệu bền vững. Lợi nhuận +10% vòng 6–7.",
          moneyChange: -5500,
          fairnessChange: 2,
          reputationChange: 3,
          bonusMultiplier: 1.1,
        },
        {
          id: "textile-4-b",
          text: "Ký hợp đồng với nhà bán sỉ lớn",
          description: "Lợi nhuận cao nhưng áp lực giá",
          moneyChange: 12000,
          fairnessChange: -3,
          reputationChange: -1,
        },
        {
          id: "textile-4-c",
          text: "Bán online thủ công tại địa phương",
          description: "Kết nối trực tiếp với khách hàng",
          moneyChange: 5000,
          fairnessChange: 1,
          reputationChange: 1,
        },
      ],
    },
    {
      round: 5,
      title: "Khủng hoảng chi phí",
      description: "Đối mặt với khó khăn tài chính.",
      options: [
        {
          id: "textile-5-a",
          text: "Giữ nguyên lương để bảo vệ người lao động",
          description: "Ưu tiên con người trước lợi nhuận",
          moneyChange: -7500,
          fairnessChange: 3,
          reputationChange: 2,
        },
        {
          id: "textile-5-b",
          text: "Cắt giảm lương tạm thời",
          description: "Tăng dòng tiền nhưng mất lòng tin",
          moneyChange: 6000,
          fairnessChange: -3,
          reputationChange: -2,
        },
        {
          id: "textile-5-c",
          text: "Xin trợ cấp từ tổ chức phi lợi nhuận",
          description: "Nhận hỗ trợ từ bên ngoài",
          moneyChange: 5000,
          fairnessChange: 1,
          reputationChange: 2,
        },
      ],
    },
    {
      round: 6,
      title: "Đầu tư công nghệ",
      description: "Quyết định về nâng cấp thiết bị.",
      options: [
        {
          id: "textile-6-a",
          text: "Đầu tư máy dệt tự động tiết kiệm nguyên liệu",
          description: "Chi phí lớn nhưng hiệu quả dài hạn. Lợi nhuận +25% ở vòng 7.",
          moneyChange: -9500,
          fairnessChange: 2,
          reputationChange: 3,
          bonusMultiplier: 1.25,
        },
        {
          id: "textile-6-b",
          text: "Nhận vốn từ nhà đầu tư không minh bạch",
          description: "Tiền nhanh nhưng đánh đổi giá trị",
          moneyChange: 15000,
          fairnessChange: -3,
          reputationChange: -3,
        },
        {
          id: "textile-6-c",
          text: "Không đầu tư, giữ nguyên hoạt động",
          description: "Duy trì ổn định",
          moneyChange: 0,
          fairnessChange: 1,
          reputationChange: 0,
        },
      ],
    },
    {
      round: 7,
      title: "Kết thúc năm tài chính",
      description: "Quyết định cuối cùng cho năm kinh doanh.",
      options: [
        {
          id: "textile-7-a",
          text: "Công bố báo cáo minh bạch, chia thưởng cho nhân viên",
          description: "Xây dựng văn hóa doanh nghiệp",
          moneyChange: -2500,
          fairnessChange: 3,
          reputationChange: 2,
        },
        {
          id: "textile-7-b",
          text: "Giảm giá hàng tồn để tối đa lợi nhuận",
          description: "Tối ưu tài chính ngắn hạn",
          moneyChange: 10000,
          fairnessChange: -2,
          reputationChange: -2,
        },
        {
          id: "textile-7-c",
          text: "Đóng góp 2% lợi nhuận cho quỹ làng nghề",
          description: "Đầu tư vào cộng đồng",
          moneyChange: -1500,
          fairnessChange: 2,
          reputationChange: 2,
        },
      ],
    },
  ],

  // SUSTAINABLE LIVESTOCK FARM
  livestock: [
    {
      round: 1,
      title: "Xây dựng chuồng trại ban đầu",
      description: "Quyết định đầu tư vào cơ sở hạ tầng chăn nuôi",
      options: [
        {
          id: "livestock-1-a",
          text: "Xây khu chuồng hiện đại đạt chuẩn vệ sinh",
          description: "Chi phí cao nhưng đảm bảo tiêu chuẩn. Hiệu suất chăn nuôi +10% vòng 3.",
          moneyChange: -25000,
          fairnessChange: 3,
          reputationChange: 3,
          bonusMultiplier: 1.1,
        },
        {
          id: "livestock-1-b",
          text: "Tận dụng chuồng cũ cải tạo lại",
          description: "Tiết kiệm chi phí nhưng chất lượng thấp. Lợi nhuận +5% ngắn hạn.",
          moneyChange: -12000,
          fairnessChange: 0,
          reputationChange: -1,
          bonusMultiplier: 1.05,
        },
        {
          id: "livestock-1-c",
          text: "Thuê trang trại địa phương để thử nghiệm",
          description: "Giảm rủi ro đầu tư ban đầu",
          moneyChange: -18000,
          fairnessChange: 2,
          reputationChange: 1,
        },
      ],
    },
    {
      round: 2,
      title: "Lựa chọn thức ăn chăn nuôi",
      description: "Quyết định nguồn thức ăn cho vật nuôi",
      options: [
        {
          id: "livestock-2-a",
          text: "Mua thức ăn hữu cơ, nguồn gốc minh bạch",
          description: "Đảm bảo chất lượng sản phẩm. Chất lượng +10% vòng 4.",
          moneyChange: -15000,
          fairnessChange: 3,
          reputationChange: 2,
          bonusMultiplier: 1.1,
        },
        {
          id: "livestock-2-b",
          text: "Sử dụng thức ăn công nghiệp giá rẻ",
          description: "Giảm chi phí nhưng ảnh hưởng sức khỏe. Lợi nhuận +8%.",
          moneyChange: -8000,
          fairnessChange: -3,
          reputationChange: -2,
          bonusMultiplier: 1.08,
        },
        {
          id: "livestock-2-c",
          text: "Tự trồng nguyên liệu thức ăn tại trang trại",
          description: "Ổn định nguồn cung dài hạn",
          moneyChange: -10000,
          fairnessChange: 2,
          reputationChange: 1,
        },
      ],
    },
    {
      round: 3,
      title: "Chính sách lao động",
      description: "Lựa chọn cách thức tuyển dụng và quản lý nhân sự",
      options: [
        {
          id: "livestock-3-a",
          text: "Trả lương công bằng & hỗ trợ bảo hiểm",
          description: "Đảm bảo quyền lợi người lao động",
          moneyChange: -10000,
          fairnessChange: 3,
          reputationChange: 3,
        },
        {
          id: "livestock-3-b",
          text: "Thuê lao động thời vụ giá rẻ",
          description: "Tiết kiệm chi phí nhưng mất ổn định",
          moneyChange: 0,
          fairnessChange: -2,
          reputationChange: -1,
        },
        {
          id: "livestock-3-c",
          text: "Hợp tác đào tạo nông dân trẻ địa phương",
          description: "Xây dựng uy tín cộng đồng +10%",
          moneyChange: -7500,
          fairnessChange: 3,
          reputationChange: 2,
        },
      ],
    },
    {
      round: 4,
      title: "Xử lý môi trường và chất thải",
      description: "Quyết định về quản lý chất thải chăn nuôi",
      options: [
        {
          id: "livestock-4-a",
          text: "Đầu tư hệ thống biogas tái tạo năng lượng",
          description: "Bền vững và tiết kiệm. Giảm chi phí duy trì 5% vòng sau.",
          moneyChange: -18000,
          fairnessChange: 3,
          reputationChange: 3,
          bonusMultiplier: 1.05,
        },
        {
          id: "livestock-4-b",
          text: "Xả thải trực tiếp ra môi trường",
          description: "Rất nguy hiểm cho uy tín! Lợi nhuận +10% ngắn hạn.",
          moneyChange: -3000,
          fairnessChange: -5,
          reputationChange: -5,
          bonusMultiplier: 1.1,
        },
        {
          id: "livestock-4-c",
          text: "Xây bể lọc tự nhiên tiết kiệm chi phí",
          description: "Giải pháp cân bằng",
          moneyChange: -9000,
          fairnessChange: 2,
          reputationChange: 2,
        },
      ],
    },
    {
      round: 5,
      title: "Chiến lược kinh doanh",
      description: "Lựa chọn kênh phân phối sản phẩm",
      options: [
        {
          id: "livestock-5-a",
          text: "Bán sản phẩm qua chuỗi siêu thị hữu cơ",
          description: "Xây dựng thương hiệu cao cấp. Lợi nhuận +12% vòng 6–7.",
          moneyChange: -15000,
          fairnessChange: 2,
          reputationChange: 3,
          bonusMultiplier: 1.12,
        },
        {
          id: "livestock-5-b",
          text: "Bán cho nhà hàng bình dân giá rẻ",
          description: "Lợi nhuận nhanh nhưng thiếu giá trị. Lợi nhuận +10% ngay.",
          moneyChange: -5000,
          fairnessChange: -2,
          reputationChange: -3,
          bonusMultiplier: 1.1,
        },
        {
          id: "livestock-5-c",
          text: "Mở cửa hàng trực tuyến Farm-to-Home",
          description: "Kết nối trực tiếp khách hàng. Khách hàng tăng 15% vòng 7.",
          moneyChange: -10000,
          fairnessChange: 3,
          reputationChange: 2,
          bonusMultiplier: 1.15,
        },
      ],
    },
    {
      round: 6,
      title: "Ứng phó dịch bệnh động vật",
      description: "Xử lý tình huống khẩn cấp về dịch bệnh",
      options: [
        {
          id: "livestock-6-a",
          text: "Tiêu hủy đúng quy định & hỗ trợ nông dân",
          description: "Trách nhiệm xã hội cao",
          moneyChange: -12000,
          fairnessChange: 3,
          reputationChange: 3,
        },
        {
          id: "livestock-6-b",
          text: "Che giấu thông tin để tránh ảnh hưởng",
          description: "Rất nguy hiểm! Có thể mất toàn bộ reputation.",
          moneyChange: 1000,
          fairnessChange: -4,
          reputationChange: -6,
        },
        {
          id: "livestock-6-c",
          text: "Công bố minh bạch & phối hợp chính quyền",
          description: "Xây dựng lòng tin dài hạn",
          moneyChange: -8000,
          fairnessChange: 2,
          reputationChange: 4,
        },
      ],
    },
    {
      round: 7,
      title: "Mở rộng quy mô trang trại",
      description: "Quyết định chiến lược phát triển cuối cùng",
      options: [
        {
          id: "livestock-7-a",
          text: "Đầu tư khu chăn nuôi hữu cơ mới",
          description: "Mở rộng bền vững",
          moneyChange: -5000,
          fairnessChange: 3,
          reputationChange: 3,
        },
        {
          id: "livestock-7-b",
          text: "Nhận vốn từ tập đoàn nước ngoài",
          description: "Lợi nhuận cao nhưng mất độc lập",
          moneyChange: 15000,
          fairnessChange: -3,
          reputationChange: -2,
        },
        {
          id: "livestock-7-c",
          text: "Giữ quy mô nhỏ, tập trung chất lượng",
          description: "Bền vững và ổn định",
          moneyChange: 5000,
          fairnessChange: 2,
          reputationChange: 2,
        },
      ],
    },
  ],

  // GREEN TECH COMPANY
  greentech: [
    {
      round: 1,
      title: "Định hướng công nghệ khởi đầu",
      description: "Lựa chọn hướng phát triển công nghệ xanh",
      options: [
        {
          id: "greentech-1-a",
          text: "Phát triển công nghệ tái chế vật liệu mới",
          description: "Đổi mới sáng tạo, chi phí cao. Tăng hiệu suất 10% vòng 3.",
          moneyChange: -25000,
          fairnessChange: 3,
          reputationChange: 3,
          bonusMultiplier: 1.1,
        },
        {
          id: "greentech-1-b",
          text: "Mua bản quyền công nghệ cũ giá rẻ",
          description: "Tiết kiệm chi phí nhưng thiếu đổi mới. Lợi nhuận +10% ngắn hạn.",
          moneyChange: -12000,
          fairnessChange: -2,
          reputationChange: -2,
          bonusMultiplier: 1.1,
        },
        {
          id: "greentech-1-c",
          text: "Hợp tác viện nghiên cứu xanh trong nước",
          description: "Giảm rủi ro phát triển công nghệ",
          moneyChange: -20000,
          fairnessChange: 2,
          reputationChange: 2,
        },
      ],
    },
    {
      round: 2,
      title: "Đầu tư cơ sở sản xuất",
      description: "Quyết định về hạ tầng sản xuất",
      options: [
        {
          id: "greentech-2-a",
          text: "Xây dựng nhà máy tiết kiệm năng lượng",
          description: "Đầu tư lớn ban đầu. Giảm chi phí vận hành vòng 5.",
          moneyChange: -30000,
          fairnessChange: 2,
          reputationChange: 3,
          bonusMultiplier: 1.05,
        },
        {
          id: "greentech-2-b",
          text: "Thuê nhà xưởng cũ cải tạo lại",
          description: "Tiết kiệm chi phí đầu tư. Lợi nhuận +5%.",
          moneyChange: -15000,
          fairnessChange: 0,
          reputationChange: -1,
          bonusMultiplier: 1.05,
        },
        {
          id: "greentech-2-c",
          text: "Liên kết sản xuất với doanh nghiệp địa phương",
          description: "Ổn định chuỗi cung ứng",
          moneyChange: -18000,
          fairnessChange: 2,
          reputationChange: 1,
        },
      ],
    },
    {
      round: 3,
      title: "Chính sách nhân sự & phát triển",
      description: "Đầu tư vào nguồn nhân lực",
      options: [
        {
          id: "greentech-3-a",
          text: "Tăng lương, đào tạo kỹ năng xanh",
          description: "Xây dựng đội ngũ chất lượng cao",
          moneyChange: -10000,
          fairnessChange: 3,
          reputationChange: 3,
        },
        {
          id: "greentech-3-b",
          text: "Cắt giảm nhân sự để tối ưu chi phí",
          description: "Tiết kiệm ngắn hạn nhưng mất tinh thần",
          moneyChange: 3000,
          fairnessChange: -2,
          reputationChange: -2,
        },
        {
          id: "greentech-3-c",
          text: "Thuê chuyên gia tư vấn năng lượng tái tạo",
          description: "Nâng cao chuyên môn. Hiệu suất +10% vòng 5.",
          moneyChange: -7500,
          fairnessChange: 1,
          reputationChange: 2,
          bonusMultiplier: 1.1,
        },
      ],
    },
    {
      round: 4,
      title: "Ứng dụng sản phẩm công nghệ xanh",
      description: "Ra mắt sản phẩm công nghệ mới",
      options: [
        {
          id: "greentech-4-a",
          text: "Ra mắt sản phẩm tái chế có chứng nhận quốc tế",
          description: "Chất lượng cao, uy tín. Lợi nhuận +20% vòng 6.",
          moneyChange: -20000,
          fairnessChange: 3,
          reputationChange: 4,
          bonusMultiplier: 1.2,
        },
        {
          id: "greentech-4-b",
          text: "Ra mắt sản phẩm giá rẻ, nguyên liệu chưa kiểm định",
          description: "Lợi nhuận nhanh nhưng rủi ro cao. Lợi nhuận +10%.",
          moneyChange: -10000,
          fairnessChange: -3,
          reputationChange: -3,
          bonusMultiplier: 1.1,
        },
        {
          id: "greentech-4-c",
          text: "Sản xuất phiên bản tiết kiệm năng lượng",
          description: "Giữ ổn định thị phần",
          moneyChange: -12000,
          fairnessChange: 2,
          reputationChange: 2,
        },
      ],
    },
    {
      round: 5,
      title: "Đối phó cạnh tranh thị trường",
      description: "Chiến lược trong môi trường cạnh tranh",
      options: [
        {
          id: "greentech-5-a",
          text: "Cạnh tranh bằng giá thấp",
          description: "Tăng thị phần nhanh nhưng giảm giá trị thương hiệu",
          moneyChange: 7000,
          fairnessChange: -2,
          reputationChange: -3,
        },
        {
          id: "greentech-5-b",
          text: "Tập trung vào giá trị xanh và minh bạch",
          description: "Xây dựng thương hiệu bền vững",
          moneyChange: -15000,
          fairnessChange: 3,
          reputationChange: 3,
        },
        {
          id: "greentech-5-c",
          text: "Hợp tác chia sẻ sáng chế với startup khác",
          description: "Tăng cơ hội đầu tư vòng 6",
          moneyChange: -10000,
          fairnessChange: 2,
          reputationChange: 2,
        },
      ],
    },
    {
      round: 6,
      title: "Gọi vốn phát triển quốc tế",
      description: "Tìm kiếm nguồn vốn đầu tư",
      options: [
        {
          id: "greentech-6-a",
          text: "Nhận đầu tư từ quỹ xanh quốc tế",
          description: "Đảm bảo giá trị bền vững",
          moneyChange: 13000,
          fairnessChange: 3,
          reputationChange: 3,
        },
        {
          id: "greentech-6-b",
          text: "Nhận đầu tư từ tập đoàn công nghiệp lớn",
          description: "Vốn lớn nhưng áp lực lợi nhuận",
          moneyChange: 20000,
          fairnessChange: -3,
          reputationChange: -4,
        },
        {
          id: "greentech-6-c",
          text: "Tự phát hành cổ phần cộng đồng",
          description: "Giữ độc lập và minh bạch",
          moneyChange: 8000,
          fairnessChange: 2,
          reputationChange: 2,
        },
      ],
    },
    {
      round: 7,
      title: "Tổng kết và mở rộng sản xuất",
      description: "Quyết định chiến lược phát triển cuối cùng",
      options: [
        {
          id: "greentech-7-a",
          text: "Đầu tư nhà máy mới sử dụng năng lượng mặt trời",
          description: "Mở rộng bền vững",
          moneyChange: 5000,
          fairnessChange: 3,
          reputationChange: 3,
        },
        {
          id: "greentech-7-b",
          text: "Tăng sản lượng nhưng giảm tiêu chuẩn kiểm định",
          description: "Lợi nhuận cao nhưng rủi ro uy tín",
          moneyChange: 27000,
          fairnessChange: -4,
          reputationChange: -3,
        },
        {
          id: "greentech-7-c",
          text: "Duy trì quy mô, tối ưu quy trình hiện có",
          description: "Ổn định và cải tiến liên tục",
          moneyChange: 15000,
          fairnessChange: 1,
          reputationChange: 2,
        },
      ],
    },
  ],

  // HANDICRAFT STORE (CỬA HÀNG THỦ CÔNG MỸ NGHỆ)
  handicraft: [
    {
      round: 1,
      title: "Nguồn hàng thủ công",
      description: "Lựa chọn nguồn cung cấp sản phẩm",
      options: [
        {
          id: "handicraft-1-a",
          text: "Mua sản phẩm từ nghệ nhân địa phương",
          description: "Chất lượng cao, hỗ trợ cộng đồng. Chất lượng +10%.",
          moneyChange: -5000,
          fairnessChange: 3,
          reputationChange: 2,
          bonusMultiplier: 1.1,
        },
        {
          id: "handicraft-1-b",
          text: "Nhập hàng giá rẻ từ xưởng Trung Quốc",
          description: "Tiết kiệm chi phí nhưng mất bản sắc. Lợi nhuận +15%.",
          moneyChange: -2000,
          fairnessChange: -2,
          reputationChange: -3,
          bonusMultiplier: 1.15,
        },
        {
          id: "handicraft-1-c",
          text: "Hợp tác chia sẻ doanh thu với nghệ nhân",
          description: "Ổn định nguồn cung dài hạn",
          moneyChange: -4000,
          fairnessChange: 2,
          reputationChange: 1,
        },
      ],
    },
    {
      round: 2,
      title: "Đầu tư cửa hàng & thiết bị",
      description: "Quyết định về không gian kinh doanh",
      options: [
        {
          id: "handicraft-2-a",
          text: "Trang trí cửa hàng thân thiện văn hóa địa phương",
          description: "Thu hút khách du lịch. Tăng lượng khách 10% vòng 4.",
          moneyChange: -3500,
          fairnessChange: 1,
          reputationChange: 3,
          bonusMultiplier: 1.1,
        },
        {
          id: "handicraft-2-b",
          text: "Mua vật liệu trưng bày cũ tái chế",
          description: "Tiết kiệm và thân thiện môi trường",
          moneyChange: -2000,
          fairnessChange: 1,
          reputationChange: 1,
        },
        {
          id: "handicraft-2-c",
          text: "Thuê mặt bằng tạm thời",
          description: "Giảm rủi ro đầu tư ban đầu",
          moneyChange: -2500,
          fairnessChange: 0,
          reputationChange: 0,
        },
      ],
    },
    {
      round: 3,
      title: "Bao bì & Thương hiệu",
      description: "Lựa chọn hình thức đóng gói sản phẩm",
      options: [
        {
          id: "handicraft-3-a",
          text: "Dùng bao bì giấy thân thiện môi trường",
          description: "Xanh và bền vững. Lợi nhuận +8% vòng 5.",
          moneyChange: -1500,
          fairnessChange: 1,
          reputationChange: 2,
          bonusMultiplier: 1.08,
        },
        {
          id: "handicraft-3-b",
          text: "Dùng túi nylon rẻ tiền",
          description: "Tiết kiệm nhưng gây ô nhiễm. Lợi nhuận +10% ngắn hạn.",
          moneyChange: -800,
          fairnessChange: -2,
          reputationChange: -2,
          bonusMultiplier: 1.1,
        },
        {
          id: "handicraft-3-c",
          text: "Bao bì vải thô, in thủ công",
          description: "Độc đáo và có giá trị",
          moneyChange: -1200,
          fairnessChange: 2,
          reputationChange: 1,
        },
      ],
    },
    {
      round: 4,
      title: "Phân phối sản phẩm",
      description: "Chọn kênh bán hàng chính",
      options: [
        {
          id: "handicraft-4-a",
          text: "Hợp tác với chuỗi cửa hàng lưu niệm",
          description: "Mở rộng thị trường nhanh",
          moneyChange: 6000,
          fairnessChange: -1,
          reputationChange: -1,
        },
        {
          id: "handicraft-4-b",
          text: "Tham gia hội chợ địa phương",
          description: "Kết nối cộng đồng",
          moneyChange: 3500,
          fairnessChange: 2,
          reputationChange: 2,
        },
        {
          id: "handicraft-4-c",
          text: "Bán online qua sàn thương mại xanh",
          description: "Tiếp cận khách hàng quan tâm bền vững",
          moneyChange: 4500,
          fairnessChange: 1,
          reputationChange: 3,
        },
      ],
    },
    {
      round: 5,
      title: "Khủng hoảng nguyên liệu",
      description: "Giá nguyên liệu thủ công tăng đột ngột",
      options: [
        {
          id: "handicraft-5-a",
          text: "Hỗ trợ nghệ nhân mua nguyên liệu mới",
          description: "Duy trì mối quan hệ lâu dài",
          moneyChange: -3000,
          fairnessChange: 3,
          reputationChange: 2,
        },
        {
          id: "handicraft-5-b",
          text: "Cắt giảm tiền công nghệ nhân",
          description: "Bảo vệ lợi nhuận nhưng mất lòng người",
          moneyChange: 2000,
          fairnessChange: -3,
          reputationChange: -2,
        },
        {
          id: "handicraft-5-c",
          text: "Tổ chức nhóm hợp tác chia sẻ vật liệu",
          description: "Giải pháp cộng đồng",
          moneyChange: -1800,
          fairnessChange: 2,
          reputationChange: 1,
        },
      ],
    },
    {
      round: 6,
      title: "Chiến lược quảng bá",
      description: "Xây dựng thương hiệu và marketing",
      options: [
        {
          id: "handicraft-6-a",
          text: "Chiến dịch Handmade with Heart",
          description: "Câu chuyện cảm xúc. Lợi nhuận +15% vòng 7.",
          moneyChange: -2500,
          fairnessChange: 2,
          reputationChange: 3,
          bonusMultiplier: 1.15,
        },
        {
          id: "handicraft-6-b",
          text: "Chạy quảng cáo online giá rẻ",
          description: "Tiếp cận nhanh nhưng ít giá trị. Lợi nhuận +10%.",
          moneyChange: -1200,
          fairnessChange: 0,
          reputationChange: -1,
          bonusMultiplier: 1.1,
        },
        {
          id: "handicraft-6-c",
          text: "Giảm giá mạnh trong mùa lễ",
          description: "Tăng doanh số ngắn hạn",
          moneyChange: 4000,
          fairnessChange: -1,
          reputationChange: -2,
        },
      ],
    },
    {
      round: 7,
      title: "Tổng kết cuối năm",
      description: "Quyết định sử dụng lợi nhuận",
      options: [
        {
          id: "handicraft-7-a",
          text: "Thưởng Tết cho nghệ nhân và nhân viên",
          description: "Tri ân và xây dựng lòng trung thành",
          moneyChange: -1000,
          fairnessChange: 3,
          reputationChange: 2,
        },
        {
          id: "handicraft-7-b",
          text: "Giữ lại lợi nhuận để mở chi nhánh",
          description: "Mở rộng quy mô kinh doanh",
          moneyChange: 2000,
          fairnessChange: 0,
          reputationChange: 1,
        },
        {
          id: "handicraft-7-c",
          text: "Tài trợ lớp học thủ công cho thanh thiếu niên",
          description: "Đầu tư vào thế hệ tương lai",
          moneyChange: -1500,
          fairnessChange: 2,
          reputationChange: 3,
        },
      ],
    },
  ],

  // SOLAR ENERGY PLANT (NHÀ MÁY NĂNG LƯỢNG MẶT TRỜI)
  solar: [
    {
      round: 1,
      title: "Địa điểm & quy mô đầu tư",
      description: "Lựa chọn vị trí xây dựng nhà máy năng lượng mặt trời",
      options: [
        {
          id: "solar-1-a",
          text: "Xây dựng nhà máy tại khu vực nông thôn có tiềm năng cao",
          description: "Hỗ trợ phát triển địa phương. Hiệu suất +10%.",
          moneyChange: -50000,
          fairnessChange: 2,
          reputationChange: 2,
          bonusMultiplier: 1.1,
        },
        {
          id: "solar-1-b",
          text: "Thuê khu đất công nghiệp giá rẻ ở xa",
          description: "Giảm chi phí nhưng xa trung tâm. Lợi nhuận +10% ngắn hạn.",
          moneyChange: -30000,
          fairnessChange: -2,
          reputationChange: -1,
          bonusMultiplier: 1.1,
        },
        {
          id: "solar-1-c",
          text: "Hợp tác cùng địa phương phát triển dự án chung",
          description: "Ổn định lâu dài, hỗ trợ cộng đồng",
          moneyChange: -40000,
          fairnessChange: 3,
          reputationChange: 1,
        },
      ],
    },
    {
      round: 2,
      title: "Lựa chọn công nghệ pin năng lượng",
      description: "Quyết định về thiết bị và công nghệ sử dụng",
      options: [
        {
          id: "solar-2-a",
          text: "Đầu tư pin hiệu suất cao, bền vững",
          description: "Chi phí cao nhưng hiệu quả lâu dài. Tăng sản lượng 15% vòng 5.",
          moneyChange: -60000,
          fairnessChange: 1,
          reputationChange: 3,
          bonusMultiplier: 1.15,
        },
        {
          id: "solar-2-b",
          text: "Nhập pin giá rẻ, tuổi thọ thấp",
          description: "Tiết kiệm đầu tư ban đầu. Lợi nhuận +15% ngắn hạn.",
          moneyChange: -35000,
          fairnessChange: -2,
          reputationChange: -3,
          bonusMultiplier: 1.15,
        },
        {
          id: "solar-2-c",
          text: "Tái sử dụng pin cũ được phục hồi",
          description: "Giảm chi phí vận hành, thân thiện môi trường",
          moneyChange: -40000,
          fairnessChange: 1,
          reputationChange: 1,
        },
      ],
    },
    {
      round: 3,
      title: "Tuyển dụng & lao động",
      description: "Chính sách nhân sự cho dự án",
      options: [
        {
          id: "solar-3-a",
          text: "Ưu tiên lao động địa phương, đào tạo miễn phí",
          description: "Xây dựng đội ngũ bền vững",
          moneyChange: -20000,
          fairnessChange: 3,
          reputationChange: 2,
        },
        {
          id: "solar-3-b",
          text: "Thuê nhân công thời vụ giá rẻ",
          description: "Giảm chi phí nhân sự. Lợi nhuận +8%.",
          moneyChange: -10000,
          fairnessChange: -2,
          reputationChange: -2,
          bonusMultiplier: 1.08,
        },
        {
          id: "solar-3-c",
          text: "Thuê chuyên gia quốc tế quản lý",
          description: "Nâng cao chuyên môn. Hiệu suất +10% vòng 4.",
          moneyChange: -25000,
          fairnessChange: 0,
          reputationChange: 2,
          bonusMultiplier: 1.1,
        },
      ],
    },
    {
      round: 4,
      title: "Chính sách bán điện & hợp tác",
      description: "Lựa chọn khách hàng và mô hình kinh doanh",
      options: [
        {
          id: "solar-4-a",
          text: "Ký hợp đồng bán điện cho doanh nghiệp lớn",
          description: "Lợi nhuận cao nhưng ít trách nhiệm xã hội",
          moneyChange: 60000,
          fairnessChange: -2,
          reputationChange: -2,
        },
        {
          id: "solar-4-b",
          text: "Cung cấp điện ưu tiên cho cộng đồng địa phương",
          description: "Hỗ trợ cộng đồng, xây dựng uy tín",
          moneyChange: 30000,
          fairnessChange: 3,
          reputationChange: 3,
        },
        {
          id: "solar-4-c",
          text: "Bán qua sàn năng lượng quốc gia (mix model)",
          description: "Cân bằng lợi nhuận và trách nhiệm",
          moneyChange: 45000,
          fairnessChange: 1,
          reputationChange: 2,
        },
      ],
    },
    {
      round: 5,
      title: "Biến động thị trường & khủng hoảng năng lượng",
      description: "Ứng phó với khủng hoảng giá năng lượng",
      options: [
        {
          id: "solar-5-a",
          text: "Giữ giá ổn định, hỗ trợ cộng đồng",
          description: "Ưu tiên con người trước lợi nhuận",
          moneyChange: -20000,
          fairnessChange: 3,
          reputationChange: 2,
        },
        {
          id: "solar-5-b",
          text: "Tăng giá điện để giữ lợi nhuận",
          description: "Tối đa hóa lợi nhuận trong khủng hoảng",
          moneyChange: 25000,
          fairnessChange: -3,
          reputationChange: -2,
        },
        {
          id: "solar-5-c",
          text: "Xin hỗ trợ từ chính phủ và đầu tư nước ngoài",
          description: "Tìm kiếm hỗ trợ bên ngoài",
          moneyChange: 15000,
          fairnessChange: 1,
          reputationChange: 1,
        },
      ],
    },
    {
      round: 6,
      title: "Chiến lược mở rộng",
      description: "Quyết định về phát triển quy mô",
      options: [
        {
          id: "solar-6-a",
          text: "Xây dựng thêm trạm năng lượng mới",
          description: "Mở rộng bền vững. Lợi nhuận +30% vòng 7.",
          moneyChange: -50000,
          fairnessChange: 2,
          reputationChange: 3,
          bonusMultiplier: 1.3,
        },
        {
          id: "solar-6-b",
          text: "Hợp tác với tập đoàn nước ngoài",
          description: "Nhận vốn và công nghệ. Lợi nhuận +25%.",
          moneyChange: -25000,
          fairnessChange: 0,
          reputationChange: 2,
          bonusMultiplier: 1.25,
        },
        {
          id: "solar-6-c",
          text: "Bán cổ phần công ty cho nhà đầu tư",
          description: "Thu vốn nhanh nhưng mất quyền kiểm soát",
          moneyChange: 40000,
          fairnessChange: -2,
          reputationChange: -1,
        },
      ],
    },
    {
      round: 7,
      title: "Tổng kết cuối năm",
      description: "Quyết định về sử dụng lợi nhuận năm",
      options: [
        {
          id: "solar-7-a",
          text: "Công bố báo cáo minh bạch & hỗ trợ trường học",
          description: "Xây dựng hình ảnh doanh nghiệp bền vững",
          moneyChange: -10000,
          fairnessChange: 3,
          reputationChange: 3,
        },
        {
          id: "solar-7-b",
          text: "Giữ lại toàn bộ lợi nhuận để tái đầu tư",
          description: "Tối ưu phát triển doanh nghiệp",
          moneyChange: 20000,
          fairnessChange: 0,
          reputationChange: 1,
        },
        {
          id: "solar-7-c",
          text: "Thưởng lớn cho ban quản lý",
          description: "Ưu tiên ban lãnh đạo",
          moneyChange: -15000,
          fairnessChange: -1,
          reputationChange: -2,
        },
      ],
    },
  ],
};

// Default decisions cho tương thích ngược
export const gameDecisions = decisionsByBusiness.coffee;

// Helper function để lấy decisions theo business type
export function getDecisionsByBusinessType(businessType: string): GameDecision[] {
  return decisionsByBusiness[businessType] || decisionsByBusiness.coffee;
}
